### ISSUE TITLE
Memory server crashes with ATL API access on verbs provider

### ISSUE THREAD

**Issue by rajakrishi** [OpenFAM/OpenFAM#145]
When running ATL API with memory server on verbs provider, it is getting crashed in application ATL side as well like:

(gdb) bt
#0  0x00007ffff61301a2 in vrb_poll_cq ()
   from /nfs/rishi/openfam-vanilla/third-party/build/lib/libfabric.so.1
#1  0x00007ffff61302cd in fi_ibv_cq_read ()
   from /nfs/rishi/openfam-vanilla/third-party/build/lib/libfabric.so.1
#2  0x00007ffff6164f1e in rxm_ep_do_progress ()
   from /nfs/rishi/openfam-vanilla/third-party/build/lib/libfabric.so.1
#3  0x00007ffff61650a1 in rxm_ep_progress ()
   from /nfs/rishi/openfam-vanilla/third-party/build/lib/libfabric.so.1
#4  0x00007ffff6104ccd in ofi_cq_progress ()
   from /nfs/rishi/openfam-vanilla/third-party/build/lib/libfabric.so.1
#5  0x00007ffff6104088 in ofi_cq_readfrom ()
   from /nfs/rishi/openfam-vanilla/third-party/build/lib/libfabric.so.1
#6  0x00007ffff7b10f80 in fi_cq_read (count=1, buf=0x7fffffffc010, cq=0x6e1430)
    at /nfs/rishi/openfam-vanilla/third-party/build/include/rdma/fi_eq.h:385
#7  openfam::fabric_completion_wait (famCtx=famCtx@entry=0x6d1cc0, ctx=ctx@entry=0x63bc90,
    ioType=ioType@entry=1) at /nfs/rishi/openfam-vanilla/src/common/fam_libfabric.cpp:620
#8  0x00007ffff77d00b4 in openfam::ATLib::ATLimpl_::fam_put_atomic (nbytes=200, offset=0,
    descriptor=0x6e1fe0, local=0x7fffffffccb0, this=0x61ae30)
    at /nfs/rishi/upstream_OpenFAM_ATL/src/fam_atl.cpp:685
#9  openfam::ATLib::fam_put_atomic (this=this@entry=0x620450, local=local@entry=0x7fffffffccb0,
    descriptor=descriptor@entry=0x6dff80, offset=offset@entry=0, nbytes=nbytes@entry=200)
    at /nfs/rishi/upstream_OpenFAM_ATL/src/fam_atl.cpp:959
#10 0x000000000040171a in main () at /nfs/rishi/upstream_OpenFAM_ATL/test/fam_atl_get_put.cpp:117

**Comment by rajakrishi** [comment]
Fixed the bug
