### ISSUE TITLE
memoryserver application for verbs provider exit with failure for negative tests

### ISSUE THREAD

**Issue by faizan-barmawer** [OpenFAM/OpenFAM#32]
We have seen issue with memoryserver application failing for negative tests:

1. Writing into invalid offset we see the below failure from memory server:
libfabric:4899:ofi_rxm:cq:rxm_cq_read_write_error():1293<debug> fi_cq_readerr: err: Operation canceled (125), prov_err: unknown)
libfabric:4899:ofi_rxm:cq:rxm_cq_read_write_error():1293<debug> fi_cq_readerr: err: Operation canceled (125), prov_err: unknown)
libfabric:4899:verbs:eq:fi_ibv_set_rnr_timer():364<warn> Unable to modify QP attribute
srun: error: hpc-cn31: task 0: Segmentation fault

2. Memory registered with read-only attribute, fam put operations does not show failures.

Need to handle these failures gracefully avoiding memory server crash.

**Comment by rajakrishi** [comment]
I observe no perm testcase failure.

#0  0x00007fa13dc9d387 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-307.el7.1.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-46.el7.x86_64 libcom_err-1.42.9-17.el7.x86_64 libevent-2.0.21-4.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libibverbs-22.4-4.el7_8.x86_64 libnl3-3.2.28-4.el7.x86_64 librdmacm-22.4-4.el7_8.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64 numactl-libs-2.0.12-5.el7.x86_64 openssl-libs-1.0.2k-19.el7.x86_64 pcre-8.32-17.el7.x86_64 yaml-cpp-0.5.1-2.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  0x00007fa13dc9d387 in raise () from /lib64/libc.so.6
#1  0x00007fa13dc9ea78 in abort () from /lib64/libc.so.6
#2  0x00007fa13e7c97d5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007fa13e7c7746 in ?? () from /lib64/libstdc++.so.6
#4  0x00007fa13e7c7773 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007fa13e7c7993 in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x00007fa14102bd1c in openfam::fam::fam_create_region (this=0x155e290, name=0x4020e3 "test1", size=8192, permissions=511,
    redundancyLevel=openfam::RAID1) at /home/rajakr/openfam-devel/src/fam-api/fam.cpp:3849
#7  0x0000000000401aa7 in main () at /home/rajakr/openfam-devel/test/unit-test/fam-api/fam_noperm_test.cpp:57
(gdb) q
-bash-4.2$
